name: CI
on: [push, pull_request]
jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v4
        with: { python-version: '3.10' }
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest flake8 black
      - name: Download GGUF (private/gated)
        env:
          HF_HUB_TOKEN: ${{ secrets.HF_HUB_TOKEN }}
        run: |
          python - <<'PY'
          import os, requests
          url = "https://huggingface.co/unsloth/gemma-3-270m-it-GGUF/resolve/main/gemma-3-270m-it-UD-Q8_K_XL.gguf"
          headers = {"Authorization": f"Bearer {os.environ['HF_HUB_TOKEN']}"}
          r = requests.get(url, headers=headers, stream=True); r.raise_for_status()
          with open("$HOME/.cache/llama_models/gemma-270m.gguf","wb") as f:
              for chunk in r.iter_content(8192):
                  f.write(chunk)
          PY
      - name: Lint
        run: flake8 src --max-line-length=100 || true
      - name: CI smoke test
        run: |
         python tests/ci_smoke_test.py --model "$HOME/.cache/llama_models/gemma-270m.gguf"
      - name: Tests
        run: pytest -q || true
      - name: Build docker
        run: docker build -t rag-serve:ci .
